name: metamask
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # Websockets
  web_socket_channel: ^2.1.0

  # For SVG image
  flutter_svg: ^1.0.3

  # For smooth page transition
  page_transition: ^2.0.5

  # For state management
  flutter_bloc: ^8.0.1

  # For internet connections
  http: ^0.13.4

  # Internationalization, numbers etc
  intl: ^0.17.0

  url_launcher: ^6.1.2
  walletconnect_dart: ^0.0.11
  google_fonts: ^3.0.1
  slider_button: ^2.0.0
  web3dart: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
